FROM frappe/bench:latest

USER root

RUN apt-get update \
	&& apt-get install --no-install-recommends -y ffmpeg \
	&& rm -rf /var/lib/apt/lists/* \
	&& localedef -i tr_TR -f UTF-8 tr_TR.UTF-8 \
	&& localedef -i en_US -f UTF-8 en_US.UTF-8

USER frappe
